version: "3"

tasks:
  docker-prune:
    desc: Remove Docker resources
    cmds:
      - docker system prune -f
    silent: true

  docker-network:
    desc: Create Docker Network
    cmds:
      - docker network create services_network
    silent: true

  kafka:
    desc: Accecss bash kafka
    cmds:
      - docker compose exec kafka bash
    silent: true

  etcd:
    desc: Accecss bash etcd
    cmds:
      - docker compose exec etcd bash
    silent: true

  # put-etcd:
  #   desc: Put etcd
  #   cmds:
  #     - curl -X POST -d '{"key": "hoge","value": "hogehoge"}' http://localhost:2378/v3/kv/put
  #   silent: true

  # read-etcd:
  #   desc: Read etcd
  #   cmds:
  #     - curl -L http://localhost:2378/v3/kv/range -X POST -d '{"key": "hoge"}'
  #   silent: true
