name: Test Service1

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  SERVICE: ./services/service-1

jobs:
  test:
    permissions:
      pull-requests: write
      actions: write
      checks: write
      contents: write

    name: Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ env.SERVICE }}/go.mod
        env:
          GO111MODULE: "on"

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          cd ${{ env.SERVICE }}
          go mod download

      - name: Run tests Service1
        run: go test -v ${{ env.SERVICE }}/... -coverprofile=coverage.out

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Staticcheck
        run: staticcheck ${{ env.SERVICE }}/...

      - name: report coverage
        uses: k1LoW/octocov-action@v0
